import { WordPressPost as Post } from '@/types/wordpress';

// Mock data for demonstration purposes
export const mockPosts: Post[] = [
  {
    id: 1,
    title: { rendered: "Getting Started with Liquid Glass Design" },
    excerpt: { rendered: "Discover the new enhanced liquid glass effects with performance-optimized animations and interactive elements.", protected: false },
    date: "2024-01-15T10:00:00Z",
    slug: "liquid-glass-design",
    link: "/liquid-glass-design",
    featured_media: 0,
    author: 1,
    categories: [1],
    tags: [],
    content: { rendered: "", protected: false },
    _embedded: {
      author: [],
      'wp:featuredmedia': [],
      'wp:term': [[]]
    },
    guid: { rendered: "" },
    date_gmt: "2024-01-15T10:00:00Z",
    modified: "2024-01-15T10:00:00Z",
    modified_gmt: "2024-01-15T10:00:00Z",
    status: "publish",
    type: "post",
    comment_status: "open",
    ping_status: "open",
    sticky: false,
    template: "",
    format: "standard",
    meta: []
  },
  {
    id: 2,
    title: { rendered: "Advanced CSS Glass Effects" },
    excerpt: { rendered: "Learn how to create stunning glass effects with CSS backdrop-filter and advanced techniques.", protected: false },
    date: "2024-01-14T15:30:00Z",
    slug: "css-glass-effects",
    link: "/css-glass-effects",
    featured_media: 0,
    author: 1,
    categories: [2],
    tags: [],
    content: { rendered: "", protected: false },
    _embedded: {
      author: [],
      'wp:featuredmedia': [],
      'wp:term': [[]]
    },
    guid: { rendered: "" },
    date_gmt: "2024-01-14T15:30:00Z",
    modified: "2024-01-14T15:30:00Z",
    modified_gmt: "2024-01-14T15:30:00Z",
    status: "publish",
    type: "post",
    comment_status: "open",
    ping_status: "open",
    sticky: false,
    template: "",
    format: "standard",
    meta: []
  },
  {
    id: 3,
    title: { rendered: "Performance Optimization Tips" },
    excerpt: { rendered: "Best practices for implementing glass effects without compromising website performance.", protected: false },
    date: "2024-01-13T09:15:00Z",
    slug: "performance-optimization",
    link: "/performance-optimization",
    featured_media: 0,
    author: 1,
    categories: [3],
    tags: [],
    content: { rendered: "", protected: false },
    _embedded: {
      author: [],
      'wp:featuredmedia': [],
      'wp:term': [[]]
    },
    guid: { rendered: "" },
    date_gmt: "2024-01-13T09:15:00Z",
    modified: "2024-01-13T09:15:00Z",
    modified_gmt: "2024-01-13T09:15:00Z",
    status: "publish",
    type: "post",
    comment_status: "open",
    ping_status: "open",
    sticky: false,
    template: "",
    format: "standard",
    meta: []
  }
];
