name = "indianyug-final"
main = ".open-next/worker.js"
compatibility_date = "2026-04-29"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "indianyug-final"

[[kv_namespaces]]
binding = "NEXT_INC_CACHE_KV"
id = "8fb37197728a4b8cbbb8bf4d1c8c4689"

[[d1_databases]]
binding = "NEXT_TAG_CACHE_D1"
database_name = "NEXT_CACHE_D1"
database_id = "41ed1906-3946-415b-a222-5480f0259f9a"

[observability]
enabled = true

[vars]
WORDPRESS_API_URL = "https://cms.indianyug.com/wp-json/wp/v2"
NEXT_PUBLIC_SITE_URL = "https://indianyug.com"
NEXT_PUBLIC_GA_ID = "G-SY4CKYK24W"
NEXT_PUBLIC_ADSENSE_CLIENT = "ca-pub-9432969048505333"
NEXT_PUBLIC_ADSENSE_SLOT_ARTICLE = "5576831162"
