name = "indianyug-final"
main = ".open-next/worker.js"
compatibility_date = "2026-04-29"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "indianyug-final"

[observability]
enabled = true
